name: Update compiled libraries
on:
  push:
    branches:
      - master
    paths:
      - native/
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            lib: skeychain.dll
          - os: macos-latest
            runtime: osx-arm64
            lib: libskeychain.dylib
          - os: ubuntu-latest 
            runtime: linux-x64
            lib: libskeychain.so
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.0
      - run: cmake --build native
      - run: cp native/${{ matrix.lib }} KeySharp/runtimes/${{ matrix.runtime }}/native/${{ matrix.lib }}
      - run: git add KeySharp/runtimes
      - run: git config --global user.name "github-actions[bot]"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git commit -m "[${{ matrix.runtime }}] Update ${{ matrix.lib }}"
      - run: git push
